substitutions:
  devicename: atomberg

esphome:
  name: $devicename

esp8266:
  board: esp01_1m


logger:
  level: INFO  # This will help hide the annoying datapoint messages
  baud_rate: 0


uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:

# Fan Power Switch
switch:
  - platform: "tuya"
    name: "$devicename Power"
    id: mybedroom_fan_switch
    switch_datapoint: 1
    internal: true

# Fan LED Switch
  - platform: "tuya"
    name: "$devicename LED"
    id: mybedroom_fan_led
    switch_datapoint: 9
    restore_mode: RESTORE_DEFAULT_OFF 

number:
  - platform: "tuya"
    name: "$devicename Speed Control"
    id: mybedroom_fan_speed
    number_datapoint: 3
    min_value: 1
    max_value: 6  # Includes all speeds including boost
    step: 1
    internal: true 

fan:
  - platform: tuya
    name: "$devicename"
    id: mybedroom_fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 6 

api:

ota:
  - platform: esphome

wifi:
  ssid: YOURSSID
  password: YOUR PASSWORD

  ap:
    ssid: $devicename
    password: "12345" #CHANGE TO A PASSWORD OF YOUR CHOICE

##THE FOLLOWING SECTION IS TO TURN ON THE FAN IN MEDIUM SPEED WHENEVR THE POWER TO THE FAN IS TURNED ON.
YOU MAY REMOVE LINE 72 TO 78 IF YOU DONT WANT THIS BEHAVIOUR ##

  on_connect:
    - delay: 1000ms 
    - switch.turn_on: 
    - delay: 500ms  
    - number.set:
          id: mybedroom_fan_speed
          value: 3 


captive_portal:
web_server:
  version: 3


sensor:
 # Wifi signal sensor.
 - platform: wifi_signal
   name: "$devicename-wifi"
   update_interval: 600s
   unit_of_measurement: '%'
   filters:
    - lambda: |-
       if (x <= -100) {
         return 0;
       } else {
         if (x >= -50) {
           return 100;
         } else {
           return 2 * (x + 100);
         }
       }
